# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Publish
      run: dotnet publish -c Release -o release

    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    # changes the base-tag in index.html from '/' to 'GhTestApp' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to AnnoyingTextApp
      run: sed -i 's/<base href="\/" \/>/<base href="\/GhTestApp\/" \/>/g' release/wwwroot/index.html
      
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: release/wwwroot

    
